# Generated by Django 5.2.6 on 2025-09-18 19:37

import billing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_invoice_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(default=billing.models.generate_invoice_number, editable=False, max_length=50, unique=True),
        ),
    ]
