# Generated by Django 5.2.6 on 2025-09-19 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_invoice_remaining_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('unpaid', 'Unpaid'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid')], default='unpaid', max_length=20),
        ),
    ]
